### ISSUE TITLE
Platform specific navigation

### ISSUE THREAD

**Issue by LegendaryB** [UltimateCodeMonkeys/CodeMonkeys#108]
@Pantheas What do you think about extending the navigation service so that we can support different views / viewmodels based on the platform?

**Comment by Pantheas** [comment]
Already implemented:

Extension method `OnPlatform([Platform])`
or [`NavigationRegistration`](https://github.com/UltimateCodeMonkeys/CodeMonkeysMVVM/blob/develop/src/Navigation/Xamarin.Forms/Navigation.Xamarin.Forms/Models/Registration/NavigationRegistration.cs) class
