### ISSUE TITLE
CodeMonkeys.DependencyInjection.* is limited to Ninject and DryIoc

### ISSUE THREAD

**Issue by LegendaryB** [UltimateCodeMonkeys/CodeMonkeys#143]
**Which package of CodeMonkeys is your request related to?**
CodeMonkeys.DependencyInjection.*

**Is your feature request related to a problem? Please describe.**
Currently a framework user can't implement new dependency injection providers.

**Describe the solution you'd like**
A solution to extend the framework dependency injection capabilities. Incl. support for accessing the underlying implementation.

**Comment by Pantheas** [comment]
Why?
He can use the interface `IDependencyContainer` and use any dependency injection framework he likes.

**Comment by LegendaryB** [comment]
Yeah I looked up what I meant with this issue. Created it a little bit ago. The user can do this but can't use the base DependencyInjection package. Its currently only consumeable by the framework internal DI packages because of the InternalsVisibleTo stuff. 

This ticket was about if it makes sense to open that/change that in some way.
